# INFO: Generate random password for TLS internal self-signed certificates

/**
This is to generate random password for internal self-signed certificates to encrypt internal flows ALB -> EC2.

Self-signed certs are used by USER_DATA during ASG refresh for each EC2 instance - in Launch Template.

Each EC2 instance will:
- Generate its own self‑signed certificate on boot.
- Store it in a Java keystore.
- Run the app with HTTPS enabled on a new port (say 8443).

The ALB:
- Will talk to instances over HTTPS:8443.
- Does not validate the certificate chain or hostname for targets—so self‑signed is fine for encryption in transit.

# TODO: No need to push a CA into ALB (there is no CA). Another option (ACM Private CA or KMS‑backed key generation can be developed later).
**/

resource "random_password" "jvx_tls_keystore" {
  length           = 20
  special          = true
  upper            = true
  lower            = true
  numeric          = true
}
 
resource "aws_secretsmanager_secret" "jvx_tls_keystore" {
  name        = "jvx-TLS-Keystore-${random_pet.string.id}"
  description = "A random secret generated by Terraform for Java Keystore. This is to encrypt internal traffic with TLS."
}

resource "aws_secretsmanager_secret_version" "jvx_tls_keystore_version" {
  secret_id     = aws_secretsmanager_secret.jvx_tls_keystore.id
  secret_string = random_password.jvx_tls_keystore.result
}


/**
# INFO: Enable Secret Rotation
# TODO: To Enable Secret Rotation, Lambda function must be defined first
resource "aws_secretsmanager_secret_rotation" "jvx_tls_keystore" {
  secret_id           = aws_secretsmanager_secret.jvx_tls_keystore.id
  rotation_lambda_arn = aws_lambda_function.jvx_tls_keystore.arn

  rotation_rules {
    automatically_after_days = 30
  }
}
**/