# ! STS API endpoint that GitHub Actions calls to assume the role is regional. `aws-region` must match where OIDC Provider have been deployed (terraform-core/aws-oidc/c5-oidc-provider.tf).

name: 03-01-JAVA-APP1-Main

# NOTE: Workflow Defaults

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

      aws_account_id:
        required: true
        type: string

      aws_region:
        required: true
        type: string

      terraform_version:
        required: true
        type: string

      role_name:
        required: true
        type: string

      tf_command:
        required: false
        type: string
        default: "apply"

permissions:
  id-token: write
  contents: read

defaults:
  run:
    shell: bash
    working-directory: ./terraform-manifests

# NOTE: Jobs

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ inputs.aws_account_id }}:role/${{ inputs.role_name }}
          aws-region: ${{ inputs.aws_region }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.terraform_version }}

      - name: Terraform Init
        run: terraform init -input=false --backend-config=env_${{ inputs.environment }}.conf

      - name: Terraform Plan
        run: terraform plan -var-file=env_${{ inputs.environment }}.tfvars

      - name: Terraform Apply/Destroy
        if: ${{ inputs.tf_command != 'plan' }} # NOTE: Required for the terraform plan to be applied with reusable workflow (when only plan is being run, don't run this.)
        run: terraform ${{ inputs.tf_command }} -auto-approve -var-file=env_${{ inputs.environment }}.tfvars
