name: 03-12-JAVA-APP1-STAG

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/03-01-java-app-main.yml
    with:
      environment: stag
      aws_role_arn: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/iac-aws-oidcRole-infra-jvx-stag
      aws_region: ${{ env.AWS_REGION }}