name: 03-12-JAVA-APP1-DEPLOY-STAG

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/03-01-java-app-main.yml
    with:
      environment: stag
      aws_account_id: "390157243794"
      aws_region: "eu-west-2"
      terraform_version: "1.13.5"
      role_name: "iac-aws-oidcRole-infra-jvx-stag"
      terraform_command: "apply"