name: 03-13-JAVA-APP1-PROD

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/03-01-java-app-main.yml
    with:
      environment: prod
      aws_account_id: "390157243794"
      aws_region: "eu-west-2"
      terraform_version: "1.13.5"
      role_name: "iac-aws-oidcRole-infra-jvx-prod"
      tf_command: "apply"